name: Build Blazor Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Azure CLI script
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          az account show

    # - name: Log in to DockerHub (optional)
    #   uses: docker/login-action@v2
    #   with:
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -f Src/TicketShare/TicketShareWeb/Dockerfile -t ticketshareweb ./Src

    # # Optional: Push to DockerHub
    # - name: Push Docker image
    #   run: |
    #     docker tag my-blazor-app:latest your-dockerhub-username/my-blazor-app:latest
    #     docker push your-dockerhub-username/my-blazor-app:latest
