name: Build Blazor Docker Image

on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read


jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Docker Login to ACR
      run: |
        az acr login --name ${{ secrets.ACR_NAME }}

    - name: Build Docker image
      run: |
        docker build -f Src/RaceAlive/RaceAliveWeb/Dockerfile -t racealiveweb ./Src

    # Optional: Push to DockerHub
    - name: Push Docker image
      run: |
        docker tag racealiveweb racealiveregistry.azurecr.io/racealiveweb:latest
        docker push racealiveregistry.azurecr.io/racealiveweb:latest

    - name: Deploy to Azure Container App
      uses: azure/container-apps-deploy-action@v1
      with:
        acrName: racealiveregistry
        containerAppName: racealiveweb
        resourceGroup: race-alive-rg
        imageToDeploy: racealiveregistry.azurecr.io/racealiveweb:latest